---
title: "Lab 7 Assignment: Group 07"
format:
  html:
    embed-resources: true
editor: visual
author: "Sarah Rosenberg Asmussen (s194689), Mette Bøge Pedersen (s194679), Caroline Amalie Bastholm Jensen (s213427), Jaime Noguera Piera (s233773), Yassine Turki (s231735)"
---

## Import data and libraries

## Data wrangling

We import necessary libraries:

```{r}
#| warning: false
library(tidyverse)
library(broom)
```

Then we import the biopsy data:

```{r}
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
biopsy
```

The dataset contains information about biopsies (rows) from breast tumors and description of these, determined by 9 attributes (columns). There is furthermore a column of the patient outcome being either benign or malignant.

## Data analysis

### Mette

```{r}
biopsy |> 
  ggplot(mapping = aes(x=clump_thickness, 
                       y=uniform_cell_size,
                       color=outcome)) +
  geom_point()
```

## Caroline

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |>  # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data
```

```{r}
pca_fit |> 
  augment(biopsy) |>  # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "red", benign = "darkgreen")
  ) +
  labs(x = "Fitted PC1",
       y = "Fited PC2")
```
